package com.qog.model;

/**
 * Nav generated by hbm2java
 */
public class Nav implements java.io.Serializable {

	private int id;
	private String text;
	private String state;
	private String iconCls;
	private String url;
	private int nid;

	public Nav() {
	}

	public Nav(int id, String text, String state, String iconCls, String url,
			int nid) {
		this.id = id;
		this.text = text;
		this.state = state;
		this.iconCls = iconCls;
		this.url = url;
		this.nid = nid;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getIconCls() {
		return this.iconCls;
	}

	public void setIconCls(String iconCls) {
		this.iconCls = iconCls;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public int getNid() {
		return this.nid;
	}

	public void setNid(int nid) {
		this.nid = nid;
	}

}
