package model;

import java.util.Date;
// Generated 2017-4-12 1:40:09 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private String studentid;
	private String name;
	private String sex;
	private String password;
	private String graduation;
	private String tel;
	private String email;

	public User(String studentid, String name, String sex, String password, String graduation, String tel, String email) {
		super();
		this.studentid = studentid;
		this.name = name;
		this.sex = sex;
		this.password = password;
		this.graduation = graduation;
		this.tel = tel;
		this.email = email;
	}

	public String getStudentid() {
		return studentid;
	}

	public void setStudentid(String studentid) {
		this.studentid = studentid;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSex() {
		return sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getGraduation() {
		return graduation;
	}

	public void setGraduation(String graduation) {
		this.graduation = graduation;
	}

	public String getTel() {
		return tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
